language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python src/runserver.py --noserver

notifications:
  email:
    recipients:
      - x3mSpeedy@gmail.com
    on_success: change
    on_failure: always
